---
apiVersion: v1
kind: Service
metadata:
  name: collection-service
  namespace: recipe-app
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 50051
      targetPort: 50051
      name: grpc
  selector:
    app: collection-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collection-service
  template:
    metadata:
      labels:
        app: collection-service
    spec:
      containers:
        - name: collection-service
          image: ghcr.io/thi-cnd/collection_service:v1.5.1 # {"$imagepolicy": "flux-system:collection-service"}
          ports:
            - containerPort: 8000
            - containerPort: 50051
          env:
            - name: SECRET_KEY_DJANGO
              valueFrom:
                secretKeyRef:
                  name: collection-service-secret
                  key: SECRET_KEY_DJANGO
            - name: DJANGO_SETTINGS_MODULE
              value: "config.settings.development"
            - name: DB_NAME
              value: "collection"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_EXCHANGE
              value: "recipemanagement"
            - name: RABBITMQ_ROUTING_KEYS_COLLECTION
              value: "collection.created,collection.updated,collection.deleted"
            - name: GRPC_HOST_RECIPE_SERVICE
              value: "recipe-service"
            - name: GRPC_PORT_RECIPE_SERVICE
              value: "9090"

---
apiVersion: v1
kind: Secret
metadata:
  name: collection-service-secret
  namespace: recipe-app
type: Opaque
data:
  SECRET_KEY_DJANGO: ZGphbmdvLWluc2VjdXJlLXZtJCs9YjgrcyY1NG02Knl6KmgmN20yYjBucV8rdWpnMzBha2dzJSt2NWp3IXBfPXhn

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collection-service-ingress
  namespace: recipe-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: collection-service.k8s.bieggerm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: collection-service
                port:
                  number: 8000

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: collection-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: collection-service
  policy:
    semver:
      range: 1.x.x

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: collection-service
  namespace: flux-system
spec:
  image: ghcr.io/thi-cnd/collection_service
  interval: 1m0s