
---
apiVersion: v1
kind: Service
metadata:
  name: feed-service
  namespace: recipe-app
spec:
  ports:
    - port: 8085
      targetPort: 8080
      name: http
  selector:
    app: feed-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      containers:
        - name: feed-service
          image: ghcr.io/thi-cnd/feed_service:latest
          ports:
            - containerPort: 8080
          env:
            - name: RECIPE_SERVICE_URL
              value: "recipe-service:9090"
            - name: COLLECTION_SERVICE_URL
              value: "http://collection-service:8000/api/v1/collections"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: password
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: FLUENTD_HOST
              value: "fluent-bit"
            - name: FLUENTD_PORT
              value: "9880"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feed-service-ingress
  namespace: recipe-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: feed-service.k8s.bieggerm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feed-service
                port:
                  number: 8085