apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: recipe-app
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/thi-cnd/frontend:v1.3.0 # {"$imagepolicy": "flux-system:frontend"}
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: recipe-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: frontend.k8s.bieggerm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api/v1/recipe
            pathType: Prefix
            backend:
              service:
                name: recipe-service
                port:
                  number: 8080
          - path: /api/v2/recipe
            pathType: Prefix
            backend:
              service:
                name: recipe-service
                port:
                  number: 8080
          - path: /api/v1/collections
            pathType: Prefix
            backend:
              service:
                name: collection-service
                port:
                  number: 8000
          - path: /api/v2/collections
            pathType: Prefix
            backend:
              service:
                name: collection-service
                port:
                  number: 8000
          - path: /api/v1/notifications
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8080
          - path: /api/v2/notifications
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8080
          - path: /api/v1/users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 8082

          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 8082

          - path: /api/v1/ingredients
            pathType: Prefix
            backend:
              service:
                name: ingredient-service
                port:
                  number: 8080
                  
          - path: /api/v2/ingredients
            pathType: Prefix
            backend:
              service:
                name: ingredient-service
                port:
                  number: 8080
          - path: /api/v1/reviews
            pathType: Prefix
            backend:
              service:
                name: review-service
                port:
                  number: 8080
          - path: /api/v1/feed
            pathType: Prefix
            backend:
              service:
                name: feed-service
                port:
                  number: 8000
          - path: /api/v1/shopping-list
            pathType: Prefix
            backend:
              service:
                name: shoppinglist-service
                port:
                  number: 3000
          - path: /api/v2/shopping-list
            pathType: Prefix
            backend:
              service:
                name: shoppinglist-service
                port:
                  number: 3000
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frontend
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: frontend
  namespace: flux-system
spec:
  image: ghcr.io/thi-cnd/frontend
  interval: 1m0s
