
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: recipe-app
spec:
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: grpc
  selector:
    app: notification-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ghcr.io/thi-cnd/notification_service:v1.5.1 # {"$imagepolicy": "flux-system:notification-service"}
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/notification"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_EXCHANGE
              value: "recipemanagement"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_ROUTING_KEYS_COLLECTION
              value: "collection.created,collection.updated,collection.deleted"
            - name: RABBITMQ_ROUTING_KEYS_REVIEW
              value: "review.created"
            - name: RABBITMQ_ROUTING_KEYS_USER
              value: "users.count"
            - name: RABBITMQ_QUEUE_COLLECTION
              value: "collection.queue"
            - name: RABBITMQ_QUEUE_REVIEW
              value: "review.queue"
            - name: RABBITMQ_QUEUE_USER
              value: "user.queue"
            - name: GRPC_USER_SERVICE_HOST
              value: "user-service"
            - name: GRPC_USER_SERVICE_PORT
              value: "8081"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notification-service-ingress
  namespace: recipe-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: notification-service.k8s.bieggerm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8080

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: notification-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: notification-service
  policy:
    semver:
      range: 1.x.x

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: notification-service
  namespace: flux-system
spec:
  image: ghcr.io/thi-cnd/notification_service
  interval: 1m0s