---
apiVersion: v1
kind: Service
metadata:
  name: recipe-service
  namespace: recipe-app
spec:
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: grpc
  selector:
    app: recipe-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-service
  template:
    metadata:
      labels:
        app: recipe-service
    spec:
      containers:
        - name: recipe-service
          image: ghcr.io/thi-cnd/recipe_service:v1.7.0 # {"$imagepolicy": "flux-system:recipe-service"}
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/recipe"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: RABBIT_HOST
              value: "rabbitmq"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"
            - name: INGREDIENT_SERVICE_ADDRESS
              value: "ingredient-service:9090"
            - name: RABBIT_EXCHANGE
              value: "recipemanagement"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "password"
            - name: REDIS_DATABASE
              value: "1"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recipe-service-ingress
  namespace: recipe-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: recipe-service.k8s.bieggerm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recipe-service
                port:
                  number: 8080

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: recipe-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: recipe-service
  policy:
    semver:
      range: 1.x.x

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: recipe-service
  namespace: flux-system
spec:
  image: ghcr.io/thi-cnd/recipe_service
  interval: 1m0s