apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: recipe-app
spec:
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: grpc
  selector:
    app: review-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: ghcr.io/thi-cnd/review_service:v1.3.3 # {"$imagepolicy": "flux-system:review-service"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 9090
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres:5432/review"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: RABBIT_HOST
              value: "rabbitmq"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"
            - name: RABBIT_EXCHANGE
              value: "recipemanagement"
            - name: USER_SERVICE_ADDRESS
              value: "user-service:9090"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: review-service-ingress
  namespace: recipe-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: review-service.k8s.bieggerm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: review-service
                port:
                  number: 8084
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: review-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: review-service
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: review-service
  namespace: flux-system
spec:
  image: ghcr.io/thi-cnd/review_service
  interval: 1m0s
