---
apiVersion: v1
kind: Service
metadata:
  name: shoppinglist-service
  namespace: recipe-app
spec:
  ports:
    - port: 3000
      name: http
    - port: 9009
      name: grpc
  selector:
    app: shopping-list-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppinglist-service
  namespace: recipe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppinglist-service
  template:
    metadata:
      labels:
        app: shoppinglist-service
    spec:
      containers:
        - name: shoppinglist-service
          image: ghcr.io/thi-cnd/shoppinglist_service:v1.3.0 # {"$imagepolicy": "flux-system:shopping-list-service"}
          ports:
            - containerPort: 3000
            - containerPort: 9009
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: password
            - name: DB_NAME
              value: shoppinglist
            - name: RABBIT_URL
              value: "amqp://guest:guest@rabbitmq:5672/"
            - name: RECIPE_SERVICE_ADDRESS
              value: "recipe-service:9090"
            - name: RABBIT_EXCHANGE
              value: recipemanagement

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopping-list-service-ingress
  namespace: recipe-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: shoppinglist.k8s.bieggerm.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shoppinglist-service
                port:
                  number: 3000

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: shopping-list-service
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: shopping-list-service
  policy:
    semver:
      range: 1.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: shopping-list-service
  namespace: flux-system
spec:
  image: ghcr.io/thi-cnd/shoppinglist_service
  interval: 1m0s
